services:
  taskmanagementsystem.database:
    image: postgres:latest
    container_name: taskmanagementsystem.database
    environment:
      - POSTGRES_DB=TaskManagementSystemDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  taskmanagementsystem.api:
    image: ${DOCKER_REGISTRY-}taskmanagementsystem
    build:
      context: .
      dockerfile: TaskManagementSystem/Dockerfile
    ports:
      - 8080:8080
      - 8081:8080
      
volumes:
  pgdata: